server:
  port: 9083

spring:
  application:
    name: payment-mock-service
  data:
    redis:
      host: 192.168.85.66
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
