server:
  port: 9082

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://192.168.85.66:3306/incident_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: 192.168.85.66
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true

fault:
  enabled: true
